In [1]:
%pip install tensorflow
%pip install numpy
%pip install -U scikit-learn

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [2]:
# sudo apt-get update
# sudo apt-get install -y python3-opencv
# pip install opencv-python matplotlib

import cv2
import matplotlib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn import metrics


In [3]:
from tensorflow.keras.datasets import cifar10
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

2024-03-11 15:25:43.134918: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-11 15:25:43.139551: I external/local_tsl/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2024-03-11 15:25:43.198173: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-03-11 15:25:44.213073: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT


In [4]:
#the images
X_train

array([[[[ 59,  62,  63],
         [ 43,  46,  45],
         [ 50,  48,  43],
         ...,
         [158, 132, 108],
         [152, 125, 102],
         [148, 124, 103]],

        [[ 16,  20,  20],
         [  0,   0,   0],
         [ 18,   8,   0],
         ...,
         [123,  88,  55],
         [119,  83,  50],
         [122,  87,  57]],

        [[ 25,  24,  21],
         [ 16,   7,   0],
         [ 49,  27,   8],
         ...,
         [118,  84,  50],
         [120,  84,  50],
         [109,  73,  42]],

        ...,

        [[208, 170,  96],
         [201, 153,  34],
         [198, 161,  26],
         ...,
         [160, 133,  70],
         [ 56,  31,   7],
         [ 53,  34,  20]],

        [[180, 139,  96],
         [173, 123,  42],
         [186, 144,  30],
         ...,
         [184, 148,  94],
         [ 97,  62,  34],
         [ 83,  53,  34]],

        [[177, 144, 116],
         [168, 129,  94],
         [179, 142,  87],
         ...,
         [216, 184, 140],
        

In [5]:
X_train.shape

(50000, 32, 32, 3)

# Preprocessing the data

In [6]:
done_list_train = []

for picture in X_train:
    greyscaled= cv2.cvtColor(picture, cv2.COLOR_BGR2GRAY) #grayscaling, shape is now: 32x32
    normalized = greyscaled/255.0 #normalize greyscale, shape is now: 32x32
    reshaped = normalized.reshape(-1, 1024) #reshape the nornalized image, shape is now 1x1024 ??
    #the first argument is the array to be reshaped, here -1 (last element), 1024 is the new shape
    done_list_train.append(reshaped) #append to the empty list

X_train=np.concatenate( done_list_train, axis=0 )
#X_train= np.array(done_list_train) #make into array and name back to X_train
X_train.shape
#X_train= np.squeeze(X_train)


done_list_test = []

for picture in X_test:
    greyscaled= cv2.cvtColor(picture, cv2.COLOR_BGR2GRAY) #grayscaling
    normalized = greyscaled/255.0 #normalize greyscale here
    reshaped = normalized.reshape(-1, 1024) #reshape the nornalized image here
    done_list_test.append(reshaped)
#X_test= np.array(done_list_test)
X_test=np.concatenate( done_list_test, axis=0 )
X_test.shape
#X_test= np.squeeze(X_test)


(10000, 1024)

In [94]:
X_train= np.squeeze(X_train)

In [8]:
X_test

array([[0.38431373, 0.38039216, 0.4       , ..., 0.33333333, 0.36078431,
        0.29411765],
       [0.92156863, 0.90588235, 0.90980392, ..., 0.70588235, 0.75294118,
        0.77647059],
       [0.76862745, 0.75686275, 0.67058824, ..., 0.02352941, 0.01568627,
        0.03137255],
       ...,
       [0.05882353, 0.05490196, 0.05098039, ..., 0.12156863, 0.1254902 ,
        0.11372549],
       [0.11764706, 0.09411765, 0.1254902 , ..., 0.41960784, 0.41960784,
        0.41176471],
       [0.30196078, 0.41176471, 0.42352941, ..., 0.42745098, 0.24705882,
        0.10196078]])

In [89]:
done_list_train = []

for picture in X_train:
    greyscaled= cv2.cvtColor(picture, cv2.COLOR_BGR2GRAY) #grayscaling, shape is now: 32x32
    normalized = greyscaled/255.0 #normalize greyscale, shape is now: 32x32
    reshaped = normalized.reshape(-1, 1024) #reshape the nornalized image, shape is now 1x1024 ??
    #the first argument is the array to be reshaped, here -1 (last element), 1024 is the new shape
    done_list_train.append(reshaped) #append to the empty list
X_train= np.array(done_list_train) #make into array and name back to X_train
X_train.shape

x = np.zeros( (X_train.shape[0], X_train.shape[1], X_train.shape[2]) )
X_train = x[:, 0, :]
print(X_train.shape)

#X_train = np.zeros( (X_train.shape[0], X_train.shape[1], X_train.shape[2]) )
#X_train = X_train[:, 0, :]
#print(X_train.shape)





(50000, 1024)


In [121]:
X_train

array([[0.24313725, 0.17647059, 0.18431373, ..., 0.68235294, 0.43921569,
        0.35294118],
       [0.69411765, 0.52941176, 0.39607843, ..., 0.53333333, 0.5372549 ,
        0.5372549 ],
       [1.        , 0.99215686, 0.99215686, ..., 0.32941176, 0.32941176,
        0.33333333],
       ...,
       [0.70196078, 0.70196078, 0.70588235, ..., 0.22352941, 0.18431373,
        0.1372549 ],
       [0.85098039, 0.83921569, 0.83529412, ..., 0.70980392, 0.72156863,
        0.7254902 ],
       [0.90980392, 0.94117647, 0.9372549 , ..., 0.69019608, 0.63921569,
        0.63529412]])

In [ ]:
done_list_test = []

for picture in X_test:
    greyscaled= cv2.cvtColor(picture, cv2.COLOR_BGR2GRAY) #grayscaling
    normalized = greyscaled/255.0 #normalize greyscale here
    reshaped = normalized.reshape(-1, 1024) #reshape the nornalized image here
    done_list_test.append(reshaped)
X_test= np.array(done_list_test)
X_test.shape

X_test = np.zeros( (X_test.shape[0], X_test.shape[1], X_test.shape[2]) )
X_test = X_test[:, 0, :]
print(X_test.shape)

In [107]:
reshaped

array([[0.30196078, 0.41176471, 0.42352941, ..., 0.42745098, 0.24705882,
        0.10196078]])

# Train a logistic regression classifier

In [13]:
type(y_train)

numpy.ndarray

In [18]:
y_train.shape

(50000, 1)

In [15]:
classes = sorted(set(y_test))
nclasses = len(classes)

TypeError: unhashable type: 'numpy.ndarray'

In [19]:
#Define classifier and fit 

classifier = LogisticRegression(tol = 0.1,
                                    solver = 'saga',
                                    multi_class = 'multinomial',
                                    random_state = 123)

model = classifier.fit(X_train, np.ravel(y_train))

#model = forest.fit(train_fold, train_y.values.ravel())


# Evaluate results

In [123]:
X_train.shape

(50000, 1024)

In [20]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [21]:
y_pred = model.predict(X_test)

classifier_metrics = metrics.classification_report(np.ravel(y_test), y_pred, labels=["airplane", "automobile", "bird","cat","deer","dog","frog","horse","ship","truck"])
print(classifier_metrics)


              precision    recall  f1-score   support

    airplane       0.00      0.00      0.00         0
  automobile       0.00      0.00      0.00         0
        bird       0.00      0.00      0.00         0
         cat       0.00      0.00      0.00         0
        deer       0.00      0.00      0.00         0
         dog       0.00      0.00      0.00         0
        frog       0.00      0.00      0.00         0
       horse       0.00      0.00      0.00         0
        ship       0.00      0.00      0.00         0
       truck       0.00      0.00      0.00         0

   micro avg       0.00      0.00      0.00         0
   macro avg       0.00      0.00      0.00         0
weighted avg       0.00      0.00      0.00         0



/home/ucloud/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ucloud/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ucloud/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1509: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 in labels with no true nor predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/ucloud/.local/lib