# CDS session 1: introduction to python

In [9]:
text_snippet = "it was the best of times, it was the worst of times"

In [10]:
#use methods on a string by saying . 
#e.g. .upper
text_snippet.upper()

'IT WAS THE BEST OF TIMES, IT WAS THE WORST OF TIMES'

In [11]:
text_snippet.lower()

'it was the best of times, it was the worst of times'

In [12]:
#split on individual words
text_snippet.split()

['it',
 'was',
 'the',
 'best',
 'of',
 'times,',
 'it',
 'was',
 'the',
 'worst',
 'of',
 'times']

In [13]:
#say what we want to split on e.g. comma
text_snippet.split(",")

['it was the best of times', ' it was the worst of times']

In [14]:
type(text_snippet.split(","))

list

# Sequence types - list

In [15]:
colours = ["blue", "green", "red"]

In [16]:
type(colours[1])

str

In [17]:
(colours[1])

'green'

In [19]:
#get last object
colours[-1]

'red'

In [22]:
user_data= ["mary", 42, "1.65"]

In [25]:
big_list= [user_data+colours]

In [26]:
big_list


[['mary', 42, '1.65', 'blue', 'green', 'red']]

In [27]:
big_list[0][1]

42

In [28]:
user_data + colours

['mary', 42, '1.65', 'blue', 'green', 'red']

In [29]:
colours.append("yellow")

In [31]:
colours

['blue', 'green', 'red', 'yellow']

In [32]:
colours.remove("green")

In [33]:
colours

['blue', 'red', 'yellow']

# tuples

In [34]:
colours_tup = ("blue", "green", "red")

In [ ]:
#tuples are fixed, they cant be e.g. appended etc. , cant change then 

In [ ]:
colours_tup.

# dictionaries

In [35]:
#acts like a key for a certain object
user_ages= {"mary":42,"john":34}
#doing {}

In [36]:
user_ages["mary"]

42

In [37]:
user_ages["john"]

34

In [38]:
#Can also use dict
new_users=dict(mary= [42, 1.65],
            john= [50, 1.80],
            alice=[24, 1.83])


In [39]:
new_users

{'mary': [42, 1.65], 'john': [50, 1.8], 'alice': [24, 1.83]}

In [41]:
new_users["mary"][1]

1.65

In [44]:
new_users2= dict(mary= {"age": 42, "height": 1.65}, 
            john= {"age": 50, "height": 1.80},
            alice = {"age":24, "height":1.83}
)

In [45]:
new_users2["mary"]["age"]

42

# number types

In [ ]:
# int = whole number (no decimals) = 2 ,4, 976, -6, 22
#floats = numbers that can have decimals = 2.3, 300.45, -5.915

In [47]:
type(2.2)

float

In [48]:
#will still be a flot even though the decimal is 0
type(2.0)

float

In [49]:
2== 2.0

True

In [50]:
#make number a float
float(2)

2.0

In [51]:
#will give only the integer number, here 2, We are NOT rounding uo
int(2.5)

2

In [52]:
10/2
#will give a float

5.0

In [54]:
#floor division, will always give an integer, 
11//2

5

# bollean types

In [55]:
True ==1

# 1 can also mean true

True

In [56]:
False== 0

#0 can also mean false

True

# Introducing ```Numpy``` arrays 

In [58]:
# Numpy = numerical python
import numpy as np
import os

In [68]:
# .. means go one step up from current directory 
filepath= os.path.join("..", "..","..", "cds-vis-data", "data", "sample-data", "sample-data-01.csv")

In [69]:
filepath

'../../../cds-vis-data/data/sample-data/sample-data-01.csv'

In [70]:
#load data
data= np.loadtxt(fname=filepath, delimiter=",")

In [71]:
data

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [72]:
type(data)

numpy.ndarray

In [74]:
data.dtype

dtype('float64')

In [75]:
data.shape
#60 rows, 40 columns 

(60, 40)

In [82]:
data[-1,-1]
#or
data[59,39]

0.0

In [84]:
#get first 10 numbers fo the first 10 rows
#arrays slice
data[0:4,0:10]

array([[0., 0., 1., 3., 1., 2., 4., 7., 8., 3.],
       [0., 1., 2., 1., 2., 1., 3., 2., 2., 6.],
       [0., 1., 1., 3., 3., 2., 6., 2., 5., 9.],
       [0., 0., 2., 0., 4., 2., 2., 1., 6., 7.]])

In [85]:
#select whole row
#its the same syntex as slice exept we dont put an end value after :
data[0,:]

array([ 0.,  0.,  1.,  3.,  1.,  2.,  4.,  7.,  8.,  3.,  3.,  3., 10.,
        5.,  7.,  4.,  7.,  7., 12., 18.,  6., 13., 11., 11.,  7.,  7.,
        4.,  6.,  8.,  8.,  4.,  4.,  5.,  7.,  3.,  4.,  2.,  3.,  0.,
        0.])

In [86]:
#select whole column
data[:,0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [87]:
#avarage score
np.mean(data)

6.14875

In [88]:
np.max(data)

20.0

In [89]:
np.min(data)

0.0

In [91]:
#axis0 = y-axis (coloumns), axis1= x-axis (rows)
#If the numbers were e.g. patient data, this would get the max score of e.g. pills taken for each day
np.max(data, axis=0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 19., 18., 17., 16., 15.,
       14., 13., 12., 11., 10.,  9.,  8.,  7.,  6.,  5.,  4.,  3.,  2.,
        1.])

In [ ]:
data[,]